name: Publish to Maven Central Repository
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Set up maven settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [
              {
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_PASSWORD }}"
              },
              {
                "id": "sonatype-nexus-staging",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_PASSWORD }}"
              }
            ]
          profiles: >
            [
              {
                "id": "sign",
                "properties": {
                  "gpg.passphrase",
                  "passphrase": "${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"
                }
              }
            ]
      
      - name: Verify package
        run: mvn -DskipTests=true --batch-mode verify
      
      - name: Release package
        run: mvn clean deploy -P release -DskipTests -Darguments=-DskipTests
