name: Publish to Maven Central Repository
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up maven settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [
              {
                "id": "sonatype-nexus-snapshots",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_PASSWORD }}"
              },
              {
                "id": "sonatype-nexus-staging",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_PASSWORD }}"
              }
            ]
          profiles: >
            [
              {
                "id": "sign",
                "activation": {
                   "activeByDefault": "true"
                },
                "properties": {
                  "gpg.passphrase": "${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}"
                }
              }
            ]
      
      - name: Release Maven package
        uses: WasiqB/maven-publish-action@v1
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
